spring:
  data:
    redis:
      host: localhost
      port: 6379
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/redis
    username: sa
    password:



logging:
  level:
    root: INFO
    org.springframework: INFO